### ISSUE TITLE
Latest tag in npm points to 3.7.7

### ISSUE THREAD

**Issue by linasburneika** [iTwin/presentation#155]
Hi,

I noticed that a recent patch release redefined a "latest" tag in npmjs registry. It has a reference to 3.7.7 version, when the actual latest stable version is 4.0.0 already published before. Tools usually depend on "latest" tag, the most usual example is to install a package without specifying version:

```
npm install @itwin/presentation-components
```

Unexpectedly it gives you 3.7.7 installed and package.json modified as follows:

```
  "dependencies": {
    "@itwin/presentation-components": "^3.7.7"
  }
```

**Comment by saskliutas** [comment]
This happened because 3.7.7 patch was released from `itwinjs-core` repository after 4.0 release. I see that the same thing has happened with AppUI packages https://www.npmjs.com/package/@itwin/appui-react?activeTab=versions

@aruniverse Do you now how we can resolve this?

**Comment by grigasp** [comment]
Just to add to this, `itwinjs-core` packages also have this issue, e.g. [core-bentley](https://www.npmjs.com/package/@itwin/core-bentley?activeTab=versions).

**Comment by aruniverse** [comment]
Ill have to check next week when I'm back. But I was under the impression that it was the default npmjs behavior to tag as latest when no dist tag was provided

**Comment by grigasp** [comment]
>  I was under the impression that it was the default npmjs behavior to tag as latest when no dist tag was provided

I suppose we shouldn't use that default when releasing from a patch branch

**Comment by grigasp** [comment]
@aruniverse, I see you fixed the tags, thanks. 

One more issue I see is that [Repository field in npm still points to `itwinjs-core` repo](https://www.npmjs.com/package/@itwin/presentation-components):
![image](https://github.com/iTwin/presentation/assets/35135765/eb574c30-a327-41a0-8734-218c6e3799f0)

I thought it's generated from `package.json` of the version with the `latest` tag, but it turns out to not be the case. Any ideas?

**Comment by aruniverse** [comment]
Hmm, thats what i thought too (fields get populated by the latest version). I wonder if a new publish would fix things, but not sure and haven't found anything yet.

**Comment by grigasp** [comment]
Publishing a new `4.0.1` version fixed the repository link. I'm closing this issue as resolved.
