### ISSUE TITLE
Incorrect category labels in property selector

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#279]
**Repro:**
1. Set up [the test app](https://github.com/iTwin/presentation/tree/master/apps/test-app) to open a class descriptor. Use [this sandbox](https://www.itwinjs.org/sandbox/grigas/class-instance-filter-dialog) as an example.
2. Open [this imodel](https://qa-developer.bentley.com/my-itwins/e51d9205-ed9c-485a-aa39-a50010787038/7876ad29-394e-45b6-89e9-7bc7a287468d/home/).
3. Open the filtering dialog.
4. Open property selector.

**Test case 1:** Type in "model" - notice there are 4 "Model" properties without any category label:
![Image](https://github.com/iTwin/presentation/assets/35135765/4c61b2c7-6beb-4cfc-be5b-dd134f2cedc0)

Expected result: 3 properties belonging to physical types should have a category label next to them, identifying the physical type they belong to.

**Test case 2:** Type in "supplier" - notice there are 3 "Supplier" properties with category label "Generic Equipment Aspect":
![Image](https://github.com/iTwin/presentation/assets/35135765/fdce7859-1334-4e6b-9898-6c20f148926b)

Expected result: The category label should contain not only the most immediate category ("Generic Equipment Aspect"), but also its ancestors. E.g. "Circuit Breaker With Disconnector | Generic Equipment Aspect".

**Comment by ViliusBa** [comment]
Does not reproduce in `next` branch

**Comment by grigasp** [comment]
> Does not reproduce in `next` branch

@ViliusBa, are you sure you closed the right issue? This one has a PR already...

**Comment by ViliusBa** [comment]
No, did this by accident 😆, will fix.
