### ISSUE TITLE
Removing rows limit for root node doesn't work

### ISSUE THREAD

**Issue by JonasDov** [iTwin/presentation#392]
Found bug while using test app:
If very first node is a "rows limit exceeded" node and one is trying to remove the rows limit for that hierarchy level it doesn't work.
Video showcasing the issue: [removing-rows-limit-if-first-doesnt-work.webm](https://github.com/iTwin/presentation/assets/100586436/29f1b1f7-69b5-4f09-9444-d5823677e103)

**Comment by grigasp** [comment]
CNR, most likely fixed with https://github.com/iTwin/presentation/pull/394. Closing.
