### ISSUE TITLE
"Contains" operator in instance filter builder should create a "like" rule with `%` on both sides of value

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#469]
The "Contains" operator should match all entries that contain given string, so user should not be forced to enter `%` on both ends of the string. On the other hand, the `GenericInstanceFilter` stores the `like` operator, which may or may not have the `%` on either end of the string. So I think `%` should be added to both ends of the string when `GenericInstanceFilter` is created using `Contains` operator.

**Comment by jasdom** [comment]
After some discussions decided that we cannot correctly handle all possible cases when converting `PresentationInstanceFilter` <-> `GenericInstanceFilter`. It's better to leave escaping/adding wildcard characters at output generation step. Added notes to `PresentationInstanceFilter` and `GenericInstanceFilter` that like operator should be handled as a contains operator: [6570](https://github.com/iTwin/itwinjs-core/pull/6570), [789](https://github.com/iTwin/appui/pull/789).
