### ISSUE TITLE
Investigate different selection modes support in `@itwin/hierarchies-react`

### ISSUE THREAD

**Issue by saskliutas** [iTwin/presentation#481]
Current `ControlledTree`  component support multiple selection modes: `Ctrl` + Select, `Shift` + Select, Single select. Need to investigate ability of supporting these modes in new implementation.

**Comment by jasdom** [comment]
Need to wait for changes to be made in iTwinUI as support for a similar feature is planned https://github.com/iTwin/iTwinUI/discussions/2027.

**Comment by grigasp** [comment]
> Need to wait for changes to be made in iTwinUI as support for a similar feature is planned [iTwin/iTwinUI#2027](https://github.com/iTwin/iTwinUI/discussions/2027).

It doesn't look like iTwinUI team is going to look into this anytime soon. Could you evaluate what it would take to implement this on our end?

**Comment by jasdom** [comment]
> > Need to wait for changes to be made in iTwinUI as support for a similar feature is planned [iTwin/iTwinUI#2027](https://github.com/iTwin/iTwinUI/discussions/2027).
> 
> It doesn't look like iTwinUI team is going to look into this anytime soon. Could you evaluate what it would take to implement this on our end?

My first guess is it would not take very long to implement on our side, however the main issue is that iTwinUI does not expose the events needed to detect whether shift or ctrl was used. We would have to either use global event listeners or wrap each node into a wrapper element and rely on event propagation to detect click events. None of these seem like good options.

**Comment by jasdom** [comment]
> > > > Need to wait for changes to be made in iTwinUI as support for a similar feature is planned [iTwin/iTwinUI#2027](https://github.com/iTwin/iTwinUI/discussions/2027).
> > > 
> > > 
> > > It doesn't look like iTwinUI team is going to look into this anytime soon. Could you evaluate what it would take to implement this on our end?
> > 
> > 
> > My first guess is it would not take very long to implement on our side, however the main issue is that iTwinUI does not expose the events needed to detect whether shift or ctrl was used. We would have to either use global event listeners or wrap each node into a wrapper element and rely on event propagation to detect click events. None of these seem like good options.
> 
> Maybe the options aren't good, but as long as they don't require us to spend a ton of time on them and can be implemented in a way that lets us remove the implementation afterwards without introducing breaking changes, I think we need to work on this. This is a show-stopper feature for us.

Okay, in that case I'll start working on a temporary implementation.
