### ISSUE TITLE
Rethink hierarchies' update on iModel changes

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#57]
At the moment we use 2 different approaches for updating hierarchies:
- when rules change, we update the whole hierarchy from the frontend
- when iModel data changes, we:
  1. detect what changed in hierarchy cache
  2. gather update-related information
  3. remove stale branches from cache
  4. send the update-related info to frontend
  5. update hierarchies on the frontend, making use of the update-related information we got from the backend.

Need to check if steps 2, 4 and 5 could be changed to what we do in case of updating after rule changes. If that provides similar performance, it would allow us to simplify and unify our update-related code.

**Comment by saskliutas** [comment]
Currently used approach looks better from UI standpoint as it loads currently visible nodes before showing new TreeModel. Reloader used when rules changes only reloads expanded nodes and other visible nodes are shown as placeholders while they are loaded. 

Need to investigate combining two approaches and try to improve TreeReloader used when rules changes to additionally load visible nodes.
