### ISSUE TITLE
itwin/presentation-components changed itwinui-react to be a peer dependency

### ISSUE THREAD

**Issue by wilmaier** [iTwin/presentation#595]
https://github.com/iTwin/presentation/commit/7402506f2e64a7cc0f00e77475e95270801b66e3

This change to make itwinui-react a peer seems to break things for pineapple and the whole strategy presented to us to make iTwinUi v2 and v3 work is that v3 is taken as a dep when the package upgrades to it.

Is it possible to roll back this change so that itwinui-react is a dependency?

**Comment by saskliutas** [comment]
I don't think that https://github.com/iTwin/presentation/pull/572 should be rolled back. In my opinion it solves a couple problems that we had before:
* Consumers usually are forced to use overrides to make sure that single version of `@itwin/itwinui-react` is used. Moving it to peer deps allows consumers to avoid that.
* It was not explicitly declared that `@itwin/presentation-components` have peer dependency on `@itiwn/itwinui-react@3` (consumers must add `ThemeProvider` from `@itwin/itwinui-react@3` in React components tree). We mentioned it as a breaking change in changelog during major bump to 5.x but it can be easily missed.

Having that in mind I believe in standard use cases moving `@itwin/itwinui-react` from direct to peer deps shouldn't have caused any problems as anyone using `@itwin/presentation-components@5` should have had `@itwin/itwinui-react@3` as a dependency already.

However, as you mention your use case is not standard and you have various overrides to manually control `@itwin/itwinui-react` versions. I don't fully understand why having `@itwin/itwinui-react` v2 and v3 would cause `@itwin/presentation-components` to resolve into multiple versions but I think you can solve this by using `.pnpmfile.cjs`:

```js
function readPackage(pkg) {
  if (pkg.name === "@itwin/presentation-components") {
    pkg.dependencies["@itwin/itwinui-react"] = "^3.0.0";
    delete pkg.peerDependencies["@itwin/itwinui-react"];
  }
}
```

**Comment by aruniverse** [comment]
> Consumers usually are forced to use overrides to make sure that single version of @itwin/itwinui-react is used.

I thought as of v3, you were able to have multiple instances of itwinui in your app to allow for easier migration. As in you should be able to use both v2 and v3 in the same app. 

imo, itwinui shouldnt have to be a peer, we should be actively working on decreasing on the number of peers we as itwinjs as a whole create

**Comment by saskliutas** [comment]
You can have both v2 and v3 at the same time but must have only one version: one for v2 and one for v3. If we have `@itwin/itwinui-react` as direct dependency this means that consumers still need to setup overrides.

ITwinUI guidelines suggest packages to consider specifying `@itwin/itwinui-react` as peer dep https://github.com/iTwin/iTwinUI/wiki/Version-conflicts#general-guidelines.

**Comment by grigasp** [comment]
@wilmaier @jason-crow @aruniverse, as @saskliutas stated, the change is in line with iTwinUI team's recommendations and we think it's okay. Do you have any objections for me closing this issue?

**Comment by grigasp** [comment]
No reply for 4 days - closing the issue.
