### ISSUE TITLE
When rendering related instances' content as array items, include their labels next to array item index

### ISSUE THREAD

**Issue by Bordoloi123** [iTwin/presentation#654]
For example, while displaying cant station point properties in the property pane, indexis displayed for each point and not the actual name as seen in OpenRail.
![image](https://github.com/iTwin/presentation/assets/127859840/68a0bc74-d09c-4bcf-b075-d7c9cffacb74)

We want the points to be displayed as
![image](https://github.com/iTwin/presentation/assets/127859840/d85653be-5c8a-492d-a62b-79131a073a8e)

**Comment by grigasp** [comment]
Hi @Bordoloi123, thanks for filing the issue. Got some questions about this:

1. Your proposed image has the category block labeled "Cant Station Points" in plural. Ours just shows class label, which is singular. Is that a problem?

2. We'll need to know which is property of the related class to use for display label. Is it identified in your schema somehow?

3. Do you expect that property to be hidden from property list when you expand the instance properties list?

4. You're proposing to show instance label **instead** of index when the label is not null. 
   - I'm worried there could be duplicate instance labels, resulting in duplicate groups.
   - In case some related instances have labels and some don't, we could end up with a weird list where some blocks have proper labels and some have `[123]` ones.

   To fix the above, I suggest always showing an index and then appending the label, if there is one, e.g. `[123] My label`. What do you think?

**Comment by grigasp** [comment]
Related: https://github.com/iTwin/itwinjs-core/issues/3790

**Comment by grigasp** [comment]
> 2. We'll need to know which is property of the related class to use for display label. Is it identified in your schema somehow?
> 
> We have decided to set the display label through IECInstance::SetDisplayLabel , on our side. So if the display label is available, you have to just render that in property pane.
> 
> 3. Do you expect that property to be hidden from property list when you expand the instance properties list?
>
> Answered in point 2.

An ECInstance doesn't have a special label property. When you use `IECInstance::SetDisplayLabel`, it attempts to find a regular property that should be used as the label (using class custom attributes or property name as the means to identify it). So question 3 remains unanswered, since the property used as a label will also appear in the properties list.

**Comment by Bordoloi123** [comment]
> > 2. We'll need to know which is property of the related class to use for display label. Is it identified in your schema somehow?
> > 
> > We have decided to set the display label through IECInstance::SetDisplayLabel , on our side. So if the display label is available, you have to just render that in property pane.
> > 
> > 3. Do you expect that property to be hidden from property list when you expand the instance properties list?
> > 
> > Answered in point 2.
> 
> An ECInstance doesn't have a special label property. When you use `IECInstance::SetDisplayLabel`, it attempts to find a regular property that should be used as the label (using class custom attributes or property name as the means to identify it). So question 3 remains unanswered, since the property used as a label will also appear in the properties list.

In that case, we will set (int the cited example) "Station" property as the display label and the property will also appear in the properties list.

**Comment by grigasp** [comment]
Sounds good. Here's what needs to be done:
- [ ] `itwinjs-core`: Add an optional `label` attribute to `NestedContentValue`.
- [ ] `imodel-native`: When creating content for related instances, also read their labels and include them in resulting nested content values.
- [ ] `presentation-components`: When creating `PropertyRecord` from `NestedContentValue` ensure the label attribute is carried over.
- [ ] `components-react`: Ensure that array items' (of type `PropertyRecord`) labels are rendered next to the index, when rendering the property grid.

**Comment by grigasp** [comment]
We should be able to implement this in `itwinjs-core@4.8` timeframe.

**Comment by Bordoloi123** [comment]
> We should be able to implement this in `itwinjs-core@4.8` timeframe.

Thank you!

**Comment by grigasp** [comment]
On hold till `itwinjs-core` 4.8 release. Then we'll need:
- bump `itwinjs-core` dev dependencies of `presentation-components` to `4.8`,
- complete https://github.com/iTwin/presentation/pull/664
- release `presentation-components`

**Comment by grigasp** [comment]
Required appui changes are released with `@itwin/components-react@4.16.0`

**Comment by grigasp** [comment]
@Bordoloi123, FYI the last missing piece was just released. You should start seeing the labels after updating the following dependencies:
- itwinjs-core `4.8`
- appui `4.16`
- presentation-components `5.4.2`

Please note that the label will not be visible if we can't find a label for the related instance. One of the ways to attach label property to instances of specific class is to use a [instance label override](https://www.itwinjs.org/presentation/customization/instancelabeloverride/) rule the ruleset you use to get the properties. With it, you can say that instance label should be set to some specific property value (through [property value specification](https://www.itwinjs.org/presentation/customization/instancelabeloverride/#property-value-specification)).

I'll keep this issue open until you confirm that everything works as expected - please let us know.

**Comment by Bordoloi123** [comment]
> @Bordoloi123, FYI the last missing piece was just released. You should start seeing the labels after updating the following dependencies:
> 
> * itwinjs-core `4.8`
> * appui `4.16`
> * presentation-components `5.4.2`
> 
> Please note that the label will not be visible if we can't find a label for the related instance. One of the ways to attach label property to instances of specific class is to use a [instance label override](https://www.itwinjs.org/presentation/customization/instancelabeloverride/) rule the ruleset you use to get the properties. With it, you can say that instance label should be set to some specific property value (through [property value specification](https://www.itwinjs.org/presentation/customization/instancelabeloverride/#property-value-specification)).
> 
> I'll keep this issue open until you confirm that everything works as expected - please let us know.

Thank you Grigas!

**Comment by grigasp** [comment]
@Bordoloi123, any update from your side? Did you get a chance to try out these changes?

**Comment by Bordoloi123** [comment]
> @Bordoloi123, any update from your side? Did you get a chance to try out these changes?

I am able to check this as I am involved with other stuff. @SachBhosale is actively working on PBIs which consume your changes.
@SachBhosale Can you pls check and confirm?

**Comment by grigasp** [comment]
Didn't hear back in 2 weeks, closing the issue. If anything is not working or working differently than you expect, please file another issue.

**Comment by SachBhosale** [comment]
@grigasp I'm sorry for not getting back to you sooner. I completely forgot about this. I will check and update you on this. Thank you.
