### ISSUE TITLE
Replace `react-select` usage with `ComboBox` from iTwinUI

### ISSUE THREAD

**Issue by saskliutas** [iTwin/presentation#701]
`react-select` usage should be replace with `ComboBox` from iTwinUI to make sure that styling is consistent. `react-select` is usage in cases where we might encounter huge amount of options and we chose to implement infinite scroll. The new suggested behavior is to limit dropdown menu options to some predetermined size and instruct user to use filtering to get relevant result. 

The new behavior removes the need for infinite scroll and should allow to use `ComboBox` from iTwinUI.

**Comment by grigasp** [comment]
https://github.com/iTwin/iTwinUI/discussions/2276

**Comment by morganadrales** [comment]
hey @grigasp, what version will this fix be pulled into?

**Comment by grigasp** [comment]
> hey [@grigasp](https://github.com/grigasp), what version will this fix be pulled into?

Hi @morganadrales. I think we can make a release tomorrow - the change will land into `@itwin/presentation-components` version `5.6.0`

**Comment by grigasp** [comment]
@morganadrales, just released: https://github.com/iTwin/presentation/releases/tag/%40itwin%2Fpresentation-components%405.6.0

**Comment by morganadrales** [comment]
@grigasp thank you so much!

**Comment by grigasp** [comment]
> [@grigasp](https://github.com/grigasp) thank you so much!

kudos to @MartynasStrazdas who made the change, I'm just the messenger :)
