### ISSUE TITLE
`components`: Lots of clicks required to edit a boolean value

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#738]
At the moment, in an editable property grid, a lot of clicks are required to edit a boolean value:
-  first click selects the property, whose value is rendered as true/false text,
-  second click enters the edit mode and renders a checkbox,
-  third click makes the change and immediately exits the edit mode, rendering true/false text again.

When the checkbox editor is used, one click should be enough to edit the value.

Considerations:
- this does not apply to all editors, so somehow we have to know when to render the editor by default and when not to do that.

**Comment by karolis-zukauskas** [comment]
Can you also test this with "toggle" editor? It would be nice if the Toggle was always visible and would require a single click to change value.

I'm referring to a property that has a presentation rule like: 
```ts 
const rule: CalculatedPropertiesSpecification = {
  // ...
  editor: { editorName: "toggle" }
}
```
