### ISSUE TITLE
Enum properties are rendered as integers instead of their display labels

### ISSUE THREAD

**Issue by karolis-zukauskas** [iTwin/presentation#763]
Enum properties are rendering as integer values. They should be rendered as display labels defined in Schema enum definition.

This can be reproduced in presentation test-app. Here property `color` should be rendered as "Red" instead of "0".
![Image](https://github.com/user-attachments/assets/abe16674-3e53-4ac1-adb9-20865a90424b)

Tested on `master` branch, commit `8c7a3064`

**Comment by grigasp** [comment]
@karolis-zukauskas, the fix was just released with `itwinjs-core` packages `4.10.1` - please give that a shot and let us know if the change fixed the issue for you.
