### ISSUE TITLE
Filter builder: Rule components are of different heights

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#787]
1. Open hierarchy level filtering dialog in presentation-test-app
2. Select some property in property selector
3. Notice that heights of components in property row are different:
   ![Image](https://github.com/user-attachments/assets/fbe470d1-d9d1-423a-808c-019d3b0f955c)

**Comment by saskliutas** [comment]
Looks like this is an issue in itwinui-react: https://github.com/iTwin/iTwinUI/issues/2356
